import images from '../assets/images';

export const gymData = [
  {
    id: 1,
    title: 'Gym Rebel',
    rating: 5.5,
    price: 250,
    favorite: false,
    image: images.gym_rebel,
    date: '02 Aug - 25 Aug, 2020',
    popular_clasess: [
      {
        id: 1,
        title: 'Fitness Class',
        price: 350,
        favorite: false,
        location: 'London, Spring st. 8',
        time: '1h 25min',
        image: images.fitness_class,
      },
      {
        id: 2,
        title: 'Fitness with some friends',
        price: 250,
        favorite: false,
        location: 'London, Spring st. 8',
        image: images.fitness_with_some_friends,
        time: '45min',
      },
      {
        id: 3,
        title: 'Yoga Class',
        price: 150,
        favorite: false,
        location: 'London, Wellness st. 23',
        time: '25min',
        image: images.yoga_class,
      },
      {
        id: 4,
        title: 'Crossfit Class',
        price: 200,
        favorite: false,
        location: 'London,Villers st. 1',
        time: '1h 30min',
        image: images.crossfit_class,
      },
    ],
  },
  {
    id: 2,
    title: 'Gym NonStop',
    rating: 3.5,
    price: 500,
    image: images.gym_non_stop,
    favorite: false,
    date: '01 Aug - 30 Aug, 2020',
    popular_clasess: [
      {
        id: 1,
        title: 'Fitness Class',
        price: 350,
        favorite: false,
        location: 'London, Spring st. 8',
        time: '1h 25min',
        image: images.fitness_class,
      },
      {
        id: 2,
        title: 'Fitness with some friends',
        price: 250,
        favorite: false,
        location: 'London, Spring st. 8',
        time: '45min',
        image: images.fitness_with_some_friends,
      },
      {
        id: 3,
        title: 'Yoga Class',
        price: 150,
        favorite: false,
        location: 'London, Wellness st. 23',
        time: '25min',
        image: images.yoga_class,
      },
    ],
  },
  {
    id: 3,
    title: 'Gym Gym',
    rating: 1.5,
    price: 150,
    image: images.gym_rebel,
    favorite: false,
    date: '05 Aug - 16 Aug, 2020',
    popular_clasess: [],
  },
];

export const popularClassesData = [
  {id: 1, image: images.popularClasses1},
  {id: 2, image: images.popularClasses2},
  {id: 3, image: images.popularClasses3},
  {id: 4, image: images.popularClasses4},
  {id: 6, image: images.popularClasses6},
  {id: 7, image: images.popularClasses7},
  {id: 8, image: images.popularClasses8},
  {id: 9, image: images.popularClasses9},
  {id: 10, image: images.popularClasses10},
];
